server:
  port: 5054

spring:
  application:
    name: customer-service

## @EnableDiscoveryClient
#### added in main spring boot application
#### prefixed with properties eureka.client

## @EnableEurekaClient
### works only with eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8770/eureka
